name: auto

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
          cache: true
      - run: go env GOCACHE
      - run: go build -v
